# Generated by Django 4.1.13 on 2023-12-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RSSFeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("description", models.TextField()),
                ("category", models.TextField()),
                ("source", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
