# Generated by Django 4.1.13 on 2023-12-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeeditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rssfeeditem',
            name='source',
        ),
        migrations.AlterField(
            model_name='rssfeeditem',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeeditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeeditem',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
